<a href="https://colab.research.google.com/github/Jordy-Rodrigues/As-formas-duas-formas-de-usar-Regress-o-Linear/blob/main/As_duas_formas_de_utilizar_Regress%C3%A3o_Linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.   Regressão Linear com a biblioteca 'statsmodels'
2.   Regressão Linear com a biblioteca 'Scikit-learn'



1. REGRESSÃO LINEAR COM A BIBLIOTECA statsmodels

In [117]:
# IMPORTAR AS BIBLIOTECAS
import pandas as pd
import numpy as np

In [118]:
# ABRIR O ARQUIVO E MOSTRAR APENAS O CABEÇALHO E AS 5 PRIMEIRAS LINHAS
data = pd.read_csv('/content/drive/MyDrive/California-Housing.csv', delimiter=',')
data.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [119]:
# VER OS DETALHES DA BASE DE DADOS
print(data.dtypes)

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
ocean_proximity        object
dtype: object


In [120]:
# VOU TAMBÉM VERIFICAR SI TEM VALORES AUSENTES OU NULOS DENTRO DA BASE DE DADOS
data.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [121]:
# EXCLUIR DUAS COLUNAS PARA DEIXAR A BASE DE DADOS PRONTA PARA UTILIZAR OS MODELOS DE REGRESSÃO
data = data.drop(['ocean_proximity','total_bedrooms'], axis=1)
data.head()

longitude  latitude  housing_median_age  total_rooms  population  \
0    -122.23     37.88                41.0        880.0       322.0   
1    -122.22     37.86                21.0       7099.0      2401.0   
2    -122.24     37.85                52.0       1467.0       496.0   
3    -122.25     37.85                52.0       1274.0       558.0   
4    -122.25     37.85                52.0       1627.0       565.0   

   households  median_income  median_house_value  
0       126.0         8.3252            452600.0  
1      1138.0         8.3014            358500.0  
2       177.0         7.2574            352100.0  
3       219.0         5.6431            341300.0  
4       259.0         3.8462            342200.0

Site do statsmodels
# https://www.statsmodels.org/stable/index.html

In [122]:
# IMPORTAR A BIBLIOTECA DE REGRESSÃO statsmodels
import statsmodels.api as sm

In [123]:
# DECLARAR O Y
y = 'median_house_value'
# EXCLUIR DA BASE DE DADOS A COLUNA median_house_value
data.drop([y], axis=1)

longitude  latitude  housing_median_age  total_rooms  population  \
0        -122.23     37.88                41.0        880.0       322.0   
1        -122.22     37.86                21.0       7099.0      2401.0   
2        -122.24     37.85                52.0       1467.0       496.0   
3        -122.25     37.85                52.0       1274.0       558.0   
4        -122.25     37.85                52.0       1627.0       565.0   
...          ...       ...                 ...          ...         ...   
20635    -121.09     39.48                25.0       1665.0       845.0   
20636    -121.21     39.49                18.0        697.0       356.0   
20637    -121.22     39.43                17.0       2254.0      1007.0   
20638    -121.32     39.43                18.0       1860.0       741.0   
20639    -121.24     39.37                16.0       2785.0      1387.0   

       households  median_income  
0           126.0         8.3252  
1          1138.0         8.3014  
2           177.0         7.2574  
3           219.0         5.6431  
4           259.0         3.8462  
...           ...            ...  
20635       330.0         1.5603  
20636       114.0         2.5568  
20637       433.0         1.7000  
20638       349.0         1.8672  
20639       530.0         2.3886  

[20640 rows x 7 columns]

In [124]:
print(y)

median_house_value


In [125]:
# PASSAR OS PARÂMETROS
modelo = sm.OLS(data[y], data.drop([y],axis=1))
res = modelo.fit()
print(res.summary())

                                 OLS Regression Results                                
Dep. Variable:     median_house_value   R-squared (uncentered):                   0.900
Model:                            OLS   Adj. R-squared (uncentered):              0.899
Method:                 Least Squares   F-statistic:                          2.639e+04
Date:                Wed, 06 Apr 2022   Prob (F-statistic):                        0.00
Time:                        22:51:00   Log-Likelihood:                     -2.6100e+05
No. Observations:               20640   AIC:                                  5.220e+05
Df Residuals:                   20633   BIC:                                  5.221e+05
Df Model:                           7                                                  
Covariance Type:            nonrobust                                                  
                         coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------

In [126]:
# FAZER UMA NORMALIZAÇÃO DOS RESULTADOS DA REGRESSÃO
from sklearn.preprocessing import StandardScaler

x = data.drop([y], axis=1)
scaler = StandardScaler()
Normalize_x = scaler.fit_transform(x)
Normalize_x = pd.DataFrame(Normalize_x, columns=x.columns)
# COLOCAR O INTERCEPT
Normalize_x['intercept'] =  1

modelo = sm.OLS(data[y], Normalize_x)
res = modelo.fit()
print(res.summary())


                            OLS Regression Results                            
Dep. Variable:     median_house_value   R-squared:                       0.632
Model:                            OLS   Adj. R-squared:                  0.632
Method:                 Least Squares   F-statistic:                     5070.
Date:                Wed, 06 Apr 2022   Prob (F-statistic):               0.00
Time:                        22:51:00   Log-Likelihood:            -2.5954e+05
No. Observations:               20640   AIC:                         5.191e+05
Df Residuals:                   20632   BIC:                         5.192e+05
Df Model:                           7                                         
Covariance Type:            nonrobust                                         
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
longitude          -8.429e+04   1434

2.   Regressão Linear com a biblioteca 'Scikit-learn'

In [127]:
# VER MEU 'X' E 'Y'
x

longitude  latitude  housing_median_age  total_rooms  population  \
0        -122.23     37.88                41.0        880.0       322.0   
1        -122.22     37.86                21.0       7099.0      2401.0   
2        -122.24     37.85                52.0       1467.0       496.0   
3        -122.25     37.85                52.0       1274.0       558.0   
4        -122.25     37.85                52.0       1627.0       565.0   
...          ...       ...                 ...          ...         ...   
20635    -121.09     39.48                25.0       1665.0       845.0   
20636    -121.21     39.49                18.0        697.0       356.0   
20637    -121.22     39.43                17.0       2254.0      1007.0   
20638    -121.32     39.43                18.0       1860.0       741.0   
20639    -121.24     39.37                16.0       2785.0      1387.0   

       households  median_income  
0           126.0         8.3252  
1          1138.0         8.3014  
2           177.0         7.2574  
3           219.0         5.6431  
4           259.0         3.8462  
...           ...            ...  
20635       330.0         1.5603  
20636       114.0         2.5568  
20637       433.0         1.7000  
20638       349.0         1.8672  
20639       530.0         2.3886  

[20640 rows x 7 columns]

In [128]:
data[y]

0        452600.0
1        358500.0
2        352100.0
3        341300.0
4        342200.0
           ...   
20635     78100.0
20636     77100.0
20637     92300.0
20638     84700.0
20639     89400.0
Name: median_house_value, Length: 20640, dtype: float64

In [129]:
# IMPORTAR OS PACOTES DA BIBLIOTECA SKLEARNING
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

# SEPARAR A BASE DE DADOS PARA TREINO E TESTE
xtreino,xteste,ytreino,yteste=train_test_split(x, data[y], test_size=0.3)
# MOSTRAR A QUANTIDADE DE LINHAS E COLUNAS DO X E Y DE TREINO E TESTE
print(xtreino.shape, xteste.shape, ytreino.shape, yteste.shape)

(14448, 7) (6192, 7) (14448,) (6192,)


In [130]:
# TREINAR O MODELO E TAMBÉM FAZER UM TESTE 
modelo = LinearRegression() 
modelo.fit(xtreino,ytreino)

base = modelo.predict(xteste)
print(base)

[193762.01067436 144269.41994872 218082.33108489 ...  94327.74530961
 313674.01840394 165016.07365662]


In [131]:
# VER AS METRICAS
from sklearn.metrics import mean_squared_error
np.sqrt(mean_squared_error(yteste,base))

70257.20654338377

In [132]:
modelo.coef_

array([-4.18478013e+04, -4.21090740e+04,  1.14858926e+03, -2.05682772e+00,
       -4.88243695e+01,  1.65948467e+02,  3.85411471e+04])

In [133]:
# USAR O PARÂMETRO DE ESCALA PADRÃO 'StandardScaler' PARA COMPARAR OS RESULTADOS DESSE MODELO COM O ANTERIOR A CIMA
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

xtreino,xteste,ytreino,yteste=train_test_split(x, data[y], test_size=0.3, random_state=0)
print(xtreino.shape, xteste.shape, ytreino.shape, yteste.shape)

scaler = StandardScaler()
xtreino_scaler = scaler.fit_transform(xtreino)
xteste_scaler = scaler.transform(xteste)

modelo = LinearRegression() # PARAMETROS(normalize=True,normalize=False,fit_intercept=True)
modelo.fit(xtreino_scaler,ytreino)

base = modelo.predict(xteste_scaler)


(14448, 7) (6192, 7) (14448,) (6192,)


In [134]:
from sklearn.metrics import mean_squared_error
np.sqrt(mean_squared_error(yteste,base))

70565.38704689054

In [135]:
modelo.coef_

array([-84500.12040533, -90145.67109481,  14361.82420896,  -3699.4259402 ,
       -46182.92026098,  53800.55045658,  73322.96306026])

In [136]:
# COMPARAR OS COEFICICÊNTES;

#                   SEM O StandardScaler
# array([-4.18478013e+04, -4.21090740e+04,  1.14858926e+03, -2.05682772e+00,
#        -4.88243695e+01,  1.65948467e+02,  3.85411471e+04])

#                   COM StandardScaler
# array([-84500.12040533, -90145.67109481,  14361.82420896,  -3699.4259402 ,
#        -46182.92026098,  53800.55045658,  73322.96306026])